/* eslint-disable @typescript-eslint/no-empty-interface */
// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
  WEBFLOW_COLLECTION_ID?: string;
  WEBFLOW_API_TOKEN?: string;
  WEBFLOW_SITE_ID?: string;
  WEBFLOW_SITE_API_TOKEN?: string;
}
